/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Admin;

import DAO.FinacasDao;
import Model.Financas;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubIJTheme;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Insets;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Pedro
 */
public class Finacas extends javax.swing.JPanel {

    /**
     * Creates new form Finacas
     */
    public Finacas() {

        initComponents();
        //   Insets insets = new Insets(1, 1, 1, 1);
        Insets insets = new Insets(1, 1, 1, 1);
        p1.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 000));
        p2.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 000));
        p1.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 000));
        p3.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 000));
        p4.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 000));
        p5.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 000));

        FinacasDao f = new FinacasDao();
        ArrayList<Financas> openFile = f.openFile();
        lDinhInvestido.setText(String.valueOf(openFile.get(0).getDinhInvestido()));
        lbLucro.setText(String.valueOf(openFile.get(0).getLucro()));
        lReceita.setText(String.valueOf(openFile.get(0).getReceita()));
        lbSaldo.setText(String.valueOf(openFile.get(0).getSaldo()));
        ldispesas.setText(String.valueOf(openFile.get(0).getDispesas()));
         double lucro = openFile.get(0).getSaldo()- openFile.get(0).getDinhInvestido()-openFile.get(0).getDispesas();
lbLucro.setText(String.valueOf(lucro));
        if(lucro<0){
            lbLucro.setForeground(Color.red);
            lLucro.setText("Prejuiso");
            lLucro.setForeground(Color.red);
        }else{
        lLucro.setText("Lucro");
            lLucro.setForeground(lbSaldo.getForeground());
        lbLucro.setForeground(lbSaldo.getForeground());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lDinhInvestido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ldispesas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lReceita = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lbSaldo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txDinheiro = new javax.swing.JTextField();
        btGardar = new javax.swing.JButton();
        p4 = new javax.swing.JPanel();
        lLucro = new javax.swing.JLabel();
        lbLucro = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setText("Finanças");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 390, 70));

        p5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setText("Dinheiro investido");

        lDinhInvestido.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lDinhInvestido.setText("000000");

        jLabel1.setFont(new java.awt.Font("Roboto Thin", 1, 48)); // NOI18N
        jLabel1.setText("$");

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lDinhInvestido, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(p5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDinhInvestido, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 250, 170));

        jLabel5.setFont(new java.awt.Font("Roboto Thin", 0, 150)); // NOI18N
        jLabel5.setText("$");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 18, -1, 140));

        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel6.setText("Total em Despesas :");

        ldispesas.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        ldispesas.setText("000000");

        jLabel8.setFont(new java.awt.Font("Roboto Thin", 1, 48)); // NOI18N
        jLabel8.setText("$");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addComponent(ldispesas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ldispesas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 250, 180));

        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel9.setText("Total da Receita :");

        lReceita.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lReceita.setText("000000");

        jLabel11.setFont(new java.awt.Font("Roboto Thin", 1, 48)); // NOI18N
        jLabel11.setText("$");

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(lReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 250, 180));

        p3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel12.setText("Saldo Total :");

        lbSaldo.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbSaldo.setText("000000");

        jLabel14.setFont(new java.awt.Font("Roboto Thin", 1, 48)); // NOI18N
        jLabel14.setText("$");

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lbSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 250, 180));

        jButton1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButton1.setText("Adicionar Valor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 240, 30));

        txDinheiro.setEnabled(false);
        txDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDinheiroActionPerformed(evt);
            }
        });
        add(txDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 240, 30));

        btGardar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btGardar.setText("Guardar");
        btGardar.setEnabled(false);
        btGardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGardarActionPerformed(evt);
            }
        });
        add(btGardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 240, -1));

        p4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lLucro.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lLucro.setText("Total De Lucro");

        lbLucro.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbLucro.setText("000000");

        jLabel16.setFont(new java.awt.Font("Roboto Thin", 1, 48)); // NOI18N
        jLabel16.setText("$");

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lLucro)
                    .addComponent(lbLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 250, 170));
    }// </editor-fold>//GEN-END:initComponents

    private void txDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDinheiroActionPerformed

    private void btGardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGardarActionPerformed
        FinacasDao f = new FinacasDao();
        ArrayList<Financas> openFile = f.openFile();

        openFile.get(0).setSaldo(openFile.get(0).getSaldo() + Double.parseDouble(txDinheiro.getText()));
        openFile.get(0).setDinhInvestido(openFile.get(0).getDinhInvestido() + Double.parseDouble(txDinheiro.getText()));
        f.insert(openFile.get(0));
        txDinheiro.setEnabled(false);
        btGardar.setEnabled(false);

    }//GEN-LAST:event_btGardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txDinheiro.setEnabled(true);
        btGardar.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lDinhInvestido;
    private javax.swing.JLabel lLucro;
    private javax.swing.JLabel lReceita;
    private javax.swing.JLabel lbLucro;
    private javax.swing.JLabel lbSaldo;
    private javax.swing.JLabel ldispesas;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JTextField txDinheiro;
    // End of variables declaration//GEN-END:variables

    public JPanel getP1() {
        return p1;
    }

    public void setP1(JPanel p1) {
        this.p1 = p1;
    }

    public JPanel getP2() {
        return p2;
    }

    public void setP2(JPanel p2) {
        this.p2 = p2;
    }

    public JPanel getP3() {
        return p3;
    }

    public void setP3(JPanel p3) {
        this.p3 = p3;
    }

    public JPanel getP4() {
        return p4;
    }

    public void setP4(JPanel p4) {
        this.p4 = p4;
    }

    public JPanel getP5() {
        return p5;
    }

    public void setP5(JPanel p5) {
        this.p5 = p5;
    }

}
