/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Admin;

import View.Gerente.AddCarro;
import View.Gerente.AdicionarFornecedor;
import View.Gerente.GerenciamentoDeprestacoes;
import View.Gerente.GerentePainel;
import View.Gerente.ListarPesquisarCarro;
import View.Gerente.ListarPrestacoes;
import View.Gerente.gStockTaxes;
import View.GerenteFrame;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.lang.System.Logger.Level;
import java.sql.SQLException;
import java.util.logging.Logger;
import javax.swing.border.Border;
import pedro.glasspanepopup.GlassPanePopup;

/**
 *
 * @author Pedro
 */
public class mess extends javax.swing.JPanel {

    GerenteFrame frame ;
    public mess( GerenteFrame frame) {
        this.frame= frame;
        initComponents();
        
          Insets insets = new Insets(1, 1, 1, 1);
       
        initComponents(); 
     //   Insets insets = new Insets(1, 1, 1, 1);
        bt1.setBorder(new  FlatLineBorder(insets, new Color(245, 104, 10), 2,020));
        bt2.setBorder(new  FlatLineBorder(insets, new Color(245, 104, 10), 2,020));
        bt3.setBorder(new  FlatLineBorder(insets, new Color(245, 104, 10), 2,020));
        b4.setBorder(new  FlatLineBorder(insets, new Color(245, 104, 10), 2,020));
        bt5.setBorder(new  FlatLineBorder(insets, new Color(245, 104, 10), 2,020));
        bt6.setBorder(new  FlatLineBorder(insets, new Color(245, 104, 10), 2,020));
       
        setOpaque(false);
        setBackground(bt3.getBackground());
        if(bt3.getBackground().equals(new Color(204,229,255))){
         Border border = new FlatLineBorder(insets, new Color(78, 170, 82), 5,010);
        setBorder(border);
        }else{
         Border border = new FlatLineBorder(insets, new Color(245, 104, 10), 5,010);
        setBorder(border);
        }
        
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt1 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1037, 264));
        setPreferredSize(new java.awt.Dimension(1037, 264));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt1.setText("Add Carro");
        bt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 200, 50));

        b4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        b4.setText("Adicionar Fornecedor");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 200, 50));

        bt2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt2.setText("Listar Carros");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 200, 50));

        bt5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt5.setText("Home");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        add(bt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 200, 50));

        bt6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt6.setText("Gestao de Taxas e Stock");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        add(bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 200, 50));

        bt3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt3.setText("Gerir Prestacoes");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 200, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed

     
            AddCarro   p1;
        try {
            p1 = new AddCarro(frame);
              p1.setSize(1000, 620);
            p1.setLocation(0,0);
            frame.getContente().setLayout(new BorderLayout());
             frame.getContente().removeAll();
             frame.getContente().add(p1, BorderLayout.CENTER );
             frame.getContente().revalidate();
             frame.getContente().repaint();
        } catch (java.sql.SQLException ex) {
            java.util.logging.Logger.getLogger(mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
          
      GlassPanePopup.closePopupAll();

    }//GEN-LAST:event_bt1ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        AdicionarFornecedor p1 = new AdicionarFornecedor(frame);

        p1.setSize(1000, 620);
        p1.setLocation(0,0);
       frame.getContente().setLayout(new BorderLayout());
       frame.getContente().removeAll();
      frame.getContente().add(p1, BorderLayout.CENTER );
        frame.getContente().revalidate();
        frame.getContente().repaint();
         GlassPanePopup.closePopupAll();
    }//GEN-LAST:event_b4ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed

      
            ListarPesquisarCarro p1;
        try {
            p1 = new ListarPesquisarCarro(frame);
             p1.setSize(1000, 620);

            p1.setLocation(0,0);
          frame.getContente().setLayout(new BorderLayout());
           frame.getContente().removeAll();
            frame.getContente().add(p1, BorderLayout.CENTER );
          frame.getContente().revalidate();
           frame.getContente().repaint();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         GlassPanePopup.closePopupAll();   
      

    }//GEN-LAST:event_bt2ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        gStockTaxes p1 = new gStockTaxes();

        p1.setSize(1000, 620);
        p1.setLocation(0,0);
        frame.getContente().setLayout(new BorderLayout());
        frame.getContente().removeAll();
       frame.getContente().add(p1, BorderLayout.CENTER );
       frame.getContente().revalidate();
       frame.getContente().repaint();
        GlassPanePopup.closePopupAll();
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        ListarPrestacoes p1 = new ListarPrestacoes(frame);
          p1.setSize(1000, 620);
        p1.setLocation(0,0);
        frame.getContente().setLayout(new BorderLayout());
        frame.getContente().removeAll();
       frame.getContente().add(p1, BorderLayout.CENTER );
       frame.getContente().revalidate();
       frame.getContente().repaint(); GlassPanePopup.closePopupAll();
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        
        GerentePainel p1;
        try {
            p1 = new GerentePainel(frame);
              p1.setSize(1000, 620);
        p1.setLocation(0,0);
        frame.getContente().setLayout(new BorderLayout());
        frame.getContente().removeAll();
       frame.getContente().add(p1, BorderLayout.CENTER );
       frame.getContente().revalidate();
       frame.getContente().repaint(); GlassPanePopup.closePopupAll();
        GlassPanePopup.closePopupAll();
        } catch (SQLException ex) {
            Logger.getLogger(mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        
    }//GEN-LAST:event_bt5ActionPerformed

    @Override
    protected void paintComponent(Graphics grphcs) {
        //super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    
     Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b4;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    // End of variables declaration//GEN-END:variables
}
