/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Admin;

import Controller.AdminController;
import DAO.AdminDao;
import DAO.FinacasDao;
import Model.Admin;
import Model.Financas;
import Model.Funcionario;
import View.ADMFrame;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Insets;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Pedro
 */
public class TelaAdmin extends javax.swing.JPanel {

    ADMFrame frame;
   

    public TelaAdmin(ADMFrame frame, Admin admin) throws SQLException, ClassNotFoundException {
        this.frame = frame;

        initComponents();

        Insets insets = new Insets(1, 1, 1, 1);
        p1.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 050));
        p2.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 050));
        p3.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 050));
        p4.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 050));
        pain.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82),2, 050));
        //=====================================
       

        l1.setText(admin.getNome() + " " + admin.getApelido());
      //==========================================================================
        AdminController cc = new AdminController(frame);
        ArrayList<Funcionario> sellectAllFuncionario = cc.sellectAllFuncionario();
        lbFuncionarios.setText(String.valueOf(sellectAllFuncionario.size()));
        
        //================================================================================
        FinacasDao dao = new FinacasDao();
        ArrayList<Financas> openFile = dao.openFile();
        lbSaldo.setText(String.valueOf(openFile.get(0).getSaldo()));
        double lucro = openFile.get(0).getSaldo()- openFile.get(0).getDinhInvestido()-openFile.get(0).getDispesas();
        lbLucro.setText(String.valueOf(lucro));
        if(lucro<0){
            lbLucro.setForeground(Color.red);
        
        }else{
        
        lbLucro.setForeground(lbFuncionarios.getForeground());
        }
        //=================================================================================
      
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        p2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbFuncionarios = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbLucro = new javax.swing.JLabel();
        MT1 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbSaldo = new javax.swing.JLabel();
        MT = new javax.swing.JLabel();
        pain = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 21, 170, 33));

        l1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        l1.setText("a");
        add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/hand-horns.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 40, 50));

        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setText("Numero De Funcionario");
        p2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 156, 37));

        lbFuncionarios.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        lbFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFuncionarios.setText("00");
        lbFuncionarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        p2.add(lbFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 120));

        p1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 200));

        p4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setText("Lucro / Prejuiso");

        lbLucro.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbLucro.setText("000000000");

        MT1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        MT1.setText("MT");

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(p4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLucro, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(MT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        p1.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 220, 200));

        p3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setText("Saldo Obtido");

        lbSaldo.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbSaldo.setText("000000000");

        MT.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        MT.setText("MT");

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addComponent(lbSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(MT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        p1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 210, 200));

        add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 710, 240));

        pain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pain.setLayout(new java.awt.BorderLayout());
        add(pain, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 160, 140));
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getP1() {
        return p1;
    }

    public void setP1(JPanel p1) {
        this.p1 = p1;
    }

    public JPanel getP2() {
        return p2;
    }

    public void setP2(JPanel p2) {
        this.p2 = p2;
    }

    public JPanel getP3() {
        return p3;
    }

    public void setP3(JPanel p3) {
        this.p3 = p3;
    }

    public JPanel getP4() {
        return p4;
    }

    public void setP4(JPanel p4) {
        this.p4 = p4;
    }

    public JPanel getPain() {
        return pain;
    }

    public void setPain(JPanel pain) {
        this.pain = pain;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MT;
    private javax.swing.JLabel MT1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel lbFuncionarios;
    private javax.swing.JLabel lbLucro;
    private javax.swing.JLabel lbSaldo;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel pain;
    // End of variables declaration//GEN-END:variables
}
