/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Gerente;

import Controller.GerenteController;
import DAO.DATABASE.CarroDao;
import DAO.PrestacoesDAO;
import DAO.StockTaxasDao;
import Model.Carro;
import Model.Prestacoes;
import Model.StockeTaxas;
import View.GerenteFrame;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Insets;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author Pedro
 */
public class GerentePainel extends javax.swing.JPanel {
    GerenteFrame frame ;
//    DecimalFormat format = new DecimalFormat("0.00");
    public GerentePainel( GerenteFrame frame) throws SQLException, ClassNotFoundException {
        this.frame = frame;
        initComponents();
       
        //----------------------------------------
        
         Insets insets = new Insets(1, 1, 1, 1);
       
         p2.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 20));
         p3.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 20));
         p4.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 20));
         p5.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 20));
        
         
         
        //------------------------------------------
       
        Calendar calendar = Calendar.getInstance();
        int diaSemana = calendar.get(Calendar.DAY_OF_WEEK);
        switch (diaSemana) {
            case 1:{
            semana.setText("Domingo");
            }
                
                break;
                   case 2:{
            semana.setText("Segunda-Feira");
            }
                
                break;
                   case 3:{
            semana.setText("Terca-Feira");
            }
                
                break;
                   case 4:{
             semana.setText("Quarta-Feira");
            }
                
                break;
                   case 5:{
             semana.setText("Quinta-Feira");
            }
                
                break;
                   case 6:{
             semana.setText("Sexta-Feira");
            }
                
                break;
                   case 7:{
             semana.setText("Sabado");
            }
                
                break;
            default:
                throw new AssertionError();
        }
        
        int dia = calendar.get(Calendar.DAY_OF_MONTH);
        int mes = calendar.get(Calendar.MONTH);
        int ano = calendar.get(Calendar.YEAR);
        lData.setText(" "+dia+" de "+mes+" "+ " de "+ano);
        
        //-------------------------------------------------
        GerenteController cc = new GerenteController(frame);
        ArrayList<Carro> sellectAllCarros = cc.sellectAllCarros();
        int i =0;
        for (Carro sellectAllCarro : sellectAllCarros) {
            if(!sellectAllCarro.isVendido()){
            i++;
            }
        }
        lCarros.setText(String.valueOf(i));
        //-------------------------------------------------
        PrestacoesDAO dAO = new PrestacoesDAO();
        ArrayList<Prestacoes> openFile = dAO.openFile();
        int j = 0;
        for (Prestacoes prestacoes : openFile) {
            if(!prestacoes.isStatus()){
            
            j++;
            }
        }
        lPrestacaoes.setText(String.valueOf(j));
        //------------------------------------------------
        StockTaxasDao ccc = new StockTaxasDao();
        ArrayList<StockeTaxas> openFile1 = ccc.openFile();
        int qntToTalCarros = openFile1.get(0).getQntToTalCarros();
        
        double lotacao = i/qntToTalCarros;
        lPorcentagem.setText( String.valueOf(lotacao*100));
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p2 = new javax.swing.JPanel();
        p3 = new javax.swing.JPanel();
        lCarros = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        lPorcentagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        lPrestacaoes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        semana = new javax.swing.JLabel();
        lData = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        p3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lCarros.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        lCarros.setText("000000000000");

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lotacao de Stock");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        p5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lPorcentagem.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        jLabel1.setText("%");

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPorcentagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Numero De Carros Disponiveis");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        p4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lPrestacaoes.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        lPrestacaoes.setText("000000000000");

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPrestacaoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPrestacaoes, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Numero De Prestacoes Abertas");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 960, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 70)); // NOI18N
        jLabel5.setText("$");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 40, 90));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 35)); // NOI18N
        jLabel6.setText("ualidade");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 160, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 35)); // NOI18N
        jLabel7.setText("&");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 30, 70));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 70)); // NOI18N
        jLabel8.setText("Q");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 50, 110));

        semana.setFont(new java.awt.Font("Roboto Medium", 0, 35)); // NOI18N
        semana.setText("Segunda-Feira");
        add(semana, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 230, 50));

        lData.setFont(new java.awt.Font("Roboto Medium", 0, 35)); // NOI18N
        add(lData, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 370, 40));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 35)); // NOI18N
        jLabel11.setText("Maputo");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 130, 40));

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 35)); // NOI18N
        jLabel10.setText("egurança ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 160, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lCarros;
    private javax.swing.JLabel lData;
    private javax.swing.JLabel lPorcentagem;
    private javax.swing.JLabel lPrestacaoes;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JLabel semana;
    // End of variables declaration//GEN-END:variables
}
